GET http://localhost:8080/book/1

###

GET http://localhost:8080/books

###

GET http://localhost:8080/book/publisher

###

GET http://localhost:8080/bookbypublisher?id=2

###

GET http://localhost:8080/book?rating=2

###

POST http://localhost:8080/book?title=tytuł&rating=2&description=opis&publisherName=wydawca

###

DELETE http://localhost:8080/book/2

###

PUT http://localhost:8080/book/1?title=tytuł_nowy&rating=3&description=opis

###

GET http://localhost:8080/author/1

###

GET http://localhost:8080/authors

###

POST http://localhost:8080/author?firstName=imię&lastName=nazwisko

###

DELETE http://localhost:8080/author/2

###

PUT http://localhost:8080/author/1?firstName=nowe imię&lastName=nowe nazwisko

###

GET http://localhost:8080/publisher/1

###

GET http://localhost:8080/publishers

###

POST http://localhost:8080/publisher?name=nazwa

###

DELETE http://localhost:8080/publisher/2

###

PUT http://localhost:8080/publisher/1?name=nowa nazwa

###

POST http://localhost:8080/person?login=nazwa&password=hasło&email=email
